%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6
%% Version source: file
-module(avatar_pb).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("avatar_pb.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type avatar_info_s2c() :: #avatar_info_s2c{}.

-type avatar_info_change_s2c() :: #avatar_info_change_s2c{}.

-type avatar_head_change_c2s() :: #avatar_head_change_c2s{}.

-type avatar_head_change_s2c() :: #avatar_head_change_s2c{}.

-type avatar_heart_beat_c2s() :: #avatar_heart_beat_c2s{}.

-type avatar_heart_beat_s2c() :: #avatar_heart_beat_s2c{}.

-type svr_open_time_c2s() :: #svr_open_time_c2s{}.

-type svr_open_time_s2c() :: #svr_open_time_s2c{}.

-export_type(['avatar_info_s2c'/0, 'avatar_info_change_s2c'/0, 'avatar_head_change_c2s'/0, 'avatar_head_change_s2c'/0, 'avatar_heart_beat_c2s'/0, 'avatar_heart_beat_s2c'/0, 'svr_open_time_c2s'/0, 'svr_open_time_s2c'/0]).
-type '$msg_name'() :: avatar_info_s2c | avatar_info_change_s2c | avatar_head_change_c2s | avatar_head_change_s2c | avatar_heart_beat_c2s | avatar_heart_beat_s2c | svr_open_time_c2s | svr_open_time_s2c.
-type '$msg'() :: avatar_info_s2c() | avatar_info_change_s2c() | avatar_head_change_c2s() | avatar_head_change_s2c() | avatar_heart_beat_c2s() | avatar_heart_beat_s2c() | svr_open_time_c2s() | svr_open_time_s2c().
-export_type(['$msg_name'/0, '$msg'/0]).

-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      avatar_info_s2c -> encode_msg_avatar_info_s2c(id(Msg, TrUserData), TrUserData);
      avatar_info_change_s2c -> encode_msg_avatar_info_change_s2c(id(Msg, TrUserData), TrUserData);
      avatar_head_change_c2s -> encode_msg_avatar_head_change_c2s(id(Msg, TrUserData), TrUserData);
      avatar_head_change_s2c -> encode_msg_avatar_head_change_s2c(id(Msg, TrUserData), TrUserData);
      avatar_heart_beat_c2s -> encode_msg_avatar_heart_beat_c2s(id(Msg, TrUserData), TrUserData);
      avatar_heart_beat_s2c -> encode_msg_avatar_heart_beat_s2c(id(Msg, TrUserData), TrUserData);
      svr_open_time_c2s -> encode_msg_svr_open_time_c2s(id(Msg, TrUserData), TrUserData);
      svr_open_time_s2c -> encode_msg_svr_open_time_s2c(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_avatar_info_s2c(Msg, TrUserData) -> encode_msg_avatar_info_s2c(Msg, <<>>, TrUserData).


encode_msg_avatar_info_s2c(#avatar_info_s2c{name = F1, id = F2, head = F3, head_border = F4, level = F5, exp = F6, vip = F7}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_int64(TrF2, <<B1/binary, 16>>, TrUserData) end,
    B3 = if F3 == undefined -> B2;
	    true -> begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end
	 end,
    B4 = if F4 == undefined -> B3;
	    true -> begin TrF4 = id(F4, TrUserData), e_type_int32(TrF4, <<B3/binary, 32>>, TrUserData) end
	 end,
    B5 = if F5 == undefined -> B4;
	    true -> begin TrF5 = id(F5, TrUserData), e_type_int32(TrF5, <<B4/binary, 40>>, TrUserData) end
	 end,
    B6 = if F6 == undefined -> B5;
	    true -> begin TrF6 = id(F6, TrUserData), e_type_int32(TrF6, <<B5/binary, 48>>, TrUserData) end
	 end,
    if F7 == undefined -> B6;
       true -> begin TrF7 = id(F7, TrUserData), e_type_int32(TrF7, <<B6/binary, 56>>, TrUserData) end
    end.

encode_msg_avatar_info_change_s2c(Msg, TrUserData) -> encode_msg_avatar_info_change_s2c(Msg, <<>>, TrUserData).


encode_msg_avatar_info_change_s2c(#avatar_info_change_s2c{name = F1, id = F2, head_id = F3, head_border = F4, level = F5, exp = F6, vip = F7}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_int64(TrF2, <<B1/binary, 16>>, TrUserData) end,
    B3 = if F3 == undefined -> B2;
	    true -> begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end
	 end,
    B4 = if F4 == undefined -> B3;
	    true -> begin TrF4 = id(F4, TrUserData), e_type_int32(TrF4, <<B3/binary, 32>>, TrUserData) end
	 end,
    B5 = if F5 == undefined -> B4;
	    true -> begin TrF5 = id(F5, TrUserData), e_type_int32(TrF5, <<B4/binary, 40>>, TrUserData) end
	 end,
    B6 = if F6 == undefined -> B5;
	    true -> begin TrF6 = id(F6, TrUserData), e_type_int32(TrF6, <<B5/binary, 48>>, TrUserData) end
	 end,
    if F7 == undefined -> B6;
       true -> begin TrF7 = id(F7, TrUserData), e_type_int32(TrF7, <<B6/binary, 56>>, TrUserData) end
    end.

encode_msg_avatar_head_change_c2s(Msg, TrUserData) -> encode_msg_avatar_head_change_c2s(Msg, <<>>, TrUserData).


encode_msg_avatar_head_change_c2s(#avatar_head_change_c2s{head_id = F1, head_border = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end
	 end,
    if F2 == undefined -> B1;
       true -> begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end
    end.

encode_msg_avatar_head_change_s2c(Msg, TrUserData) -> encode_msg_avatar_head_change_s2c(Msg, <<>>, TrUserData).


encode_msg_avatar_head_change_s2c(#avatar_head_change_s2c{result = F1, head_id = F2, head_border = F3}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end
	 end,
    B2 = if F2 == undefined -> B1;
	    true -> begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end
	 end,
    if F3 == undefined -> B2;
       true -> begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end
    end.

encode_msg_avatar_heart_beat_c2s(Msg, TrUserData) -> encode_msg_avatar_heart_beat_c2s(Msg, <<>>, TrUserData).


encode_msg_avatar_heart_beat_c2s(#avatar_heart_beat_c2s{svr_time = F1}, Bin, TrUserData) -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end.

encode_msg_avatar_heart_beat_s2c(Msg, TrUserData) -> encode_msg_avatar_heart_beat_s2c(Msg, <<>>, TrUserData).


encode_msg_avatar_heart_beat_s2c(#avatar_heart_beat_s2c{svr_time = F1}, Bin, TrUserData) -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end.

encode_msg_svr_open_time_c2s(_Msg, _TrUserData) -> <<>>.

encode_msg_svr_open_time_s2c(Msg, TrUserData) -> encode_msg_svr_open_time_s2c(Msg, <<>>, TrUserData).


encode_msg_svr_open_time_s2c(#svr_open_time_s2c{open_time = F1}, Bin, TrUserData) -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) -> Utf8 = unicode:characters_to_binary(S), Bin2 = e_varint(byte_size(Utf8), Bin), <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) -> Bin2 = e_varint(byte_size(Bytes), Bin), <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) -> BytesBin = iolist_to_binary(Bytes), Bin2 = e_varint(byte_size(BytesBin), Bin), <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
	     {varint, FNum, N} -> BinF = e_varint(FNum bsl 3, Bin), e_varint(N, BinF);
	     {length_delimited, FNum, Data} -> BinF = e_varint(FNum bsl 3 bor 2, Bin), BinL = e_varint(byte_size(Data), BinF), <<BinL/binary, Data/binary>>;
	     {group, FNum, GroupFields} -> Bin1 = e_varint(FNum bsl 3 bor 3, Bin), Bin2 = e_unknown_elems(GroupFields, Bin1), e_varint(FNum bsl 3 bor 4, Bin2);
	     {fixed32, FNum, V} -> BinF = e_varint(FNum bsl 3 bor 5, Bin), <<BinF/binary, V:32/little>>;
	     {fixed64, FNum, V} -> BinF = e_varint(FNum bsl 3 bor 1, Bin), <<BinF/binary, V:64/little>>
	   end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) -> Bin2 = <<Bin/binary, (N band 127 bor 128)>>, e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) -> TrUserData = proplists:get_value(user_data, Opts), decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(avatar_info_s2c, Bin, TrUserData) -> id(decode_msg_avatar_info_s2c(Bin, TrUserData), TrUserData);
decode_msg_2_doit(avatar_info_change_s2c, Bin, TrUserData) -> id(decode_msg_avatar_info_change_s2c(Bin, TrUserData), TrUserData);
decode_msg_2_doit(avatar_head_change_c2s, Bin, TrUserData) -> id(decode_msg_avatar_head_change_c2s(Bin, TrUserData), TrUserData);
decode_msg_2_doit(avatar_head_change_s2c, Bin, TrUserData) -> id(decode_msg_avatar_head_change_s2c(Bin, TrUserData), TrUserData);
decode_msg_2_doit(avatar_heart_beat_c2s, Bin, TrUserData) -> id(decode_msg_avatar_heart_beat_c2s(Bin, TrUserData), TrUserData);
decode_msg_2_doit(avatar_heart_beat_s2c, Bin, TrUserData) -> id(decode_msg_avatar_heart_beat_s2c(Bin, TrUserData), TrUserData);
decode_msg_2_doit(svr_open_time_c2s, Bin, TrUserData) -> id(decode_msg_svr_open_time_c2s(Bin, TrUserData), TrUserData);
decode_msg_2_doit(svr_open_time_s2c, Bin, TrUserData) -> id(decode_msg_svr_open_time_s2c(Bin, TrUserData), TrUserData).



decode_msg_avatar_info_s2c(Bin, TrUserData) ->
    dfp_read_field_def_avatar_info_s2c(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_avatar_info_s2c(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_name(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_head(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_head_border(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_level(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_exp(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<56, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_s2c_vip(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #avatar_info_s2c{name = F@_1, id = F@_2, head = F@_3, head_border = F@_4, level = F@_5, exp = F@_6, vip = F@_7};
dfp_read_field_def_avatar_info_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dg_read_field_def_avatar_info_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

dg_read_field_def_avatar_info_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_avatar_info_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dg_read_field_def_avatar_info_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_avatar_info_s2c_name(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      16 -> d_field_avatar_info_s2c_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      24 -> d_field_avatar_info_s2c_head(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      32 -> d_field_avatar_info_s2c_head_border(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      40 -> d_field_avatar_info_s2c_level(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      48 -> d_field_avatar_info_s2c_exp(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      56 -> d_field_avatar_info_s2c_vip(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_info_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    1 -> skip_64_avatar_info_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    2 -> skip_length_delimited_avatar_info_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    3 -> skip_group_avatar_info_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    5 -> skip_32_avatar_info_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData)
	  end
    end;
dg_read_field_def_avatar_info_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #avatar_info_s2c{name = F@_1, id = F@_2, head = F@_3, head_border = F@_4, level = F@_5, exp = F@_6, vip = F@_7}.

d_field_avatar_info_s2c_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_avatar_info_s2c_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_s2c_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_avatar_info_s2c_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_s2c_head(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_avatar_info_s2c_head(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_head(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_s2c_head_border(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_s2c_head_border(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_head_border(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_s2c_level(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_s2c_level(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_level(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, TrUserData).

d_field_avatar_info_s2c_exp(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_avatar_info_s2c_exp(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_exp(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, TrUserData).

d_field_avatar_info_s2c_vip(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_avatar_info_s2c_vip(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_s2c_vip(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, TrUserData).

skip_varint_avatar_info_s2c(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> skip_varint_avatar_info_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_varint_avatar_info_s2c(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_length_delimited_avatar_info_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    skip_length_delimited_avatar_info_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_length_delimited_avatar_info_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_info_s2c(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_group_avatar_info_s2c(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_info_s2c(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_32_avatar_info_s2c(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_64_avatar_info_s2c(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

decode_msg_avatar_info_change_s2c(Bin, TrUserData) ->
    dfp_read_field_def_avatar_info_change_s2c(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData),
					      TrUserData).

dfp_read_field_def_avatar_info_change_s2c(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_name(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_head_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_head_border(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_level(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_exp(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<56, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_avatar_info_change_s2c_vip(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_avatar_info_change_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #avatar_info_change_s2c{name = F@_1, id = F@_2, head_id = F@_3, head_border = F@_4, level = F@_5, exp = F@_6, vip = F@_7};
dfp_read_field_def_avatar_info_change_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dg_read_field_def_avatar_info_change_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

dg_read_field_def_avatar_info_change_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_avatar_info_change_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dg_read_field_def_avatar_info_change_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_avatar_info_change_s2c_name(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      16 -> d_field_avatar_info_change_s2c_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      24 -> d_field_avatar_info_change_s2c_head_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      32 -> d_field_avatar_info_change_s2c_head_border(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      40 -> d_field_avatar_info_change_s2c_level(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      48 -> d_field_avatar_info_change_s2c_exp(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      56 -> d_field_avatar_info_change_s2c_vip(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_info_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    1 -> skip_64_avatar_info_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    2 -> skip_length_delimited_avatar_info_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    3 -> skip_group_avatar_info_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    5 -> skip_32_avatar_info_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData)
	  end
    end;
dg_read_field_def_avatar_info_change_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #avatar_info_change_s2c{name = F@_1, id = F@_2, head_id = F@_3, head_border = F@_4, level = F@_5, exp = F@_6, vip = F@_7}.

d_field_avatar_info_change_s2c_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_change_s2c_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_change_s2c_head_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_head_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_head_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_change_s2c_head_border(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_head_border(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_head_border(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, TrUserData).

d_field_avatar_info_change_s2c_level(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_level(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_level(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, TrUserData).

d_field_avatar_info_change_s2c_exp(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_exp(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_exp(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, TrUserData).

d_field_avatar_info_change_s2c_vip(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_avatar_info_change_s2c_vip(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_avatar_info_change_s2c_vip(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_info_change_s2c(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, TrUserData).

skip_varint_avatar_info_change_s2c(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> skip_varint_avatar_info_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_varint_avatar_info_change_s2c(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_length_delimited_avatar_info_change_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    skip_length_delimited_avatar_info_change_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_length_delimited_avatar_info_change_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_info_change_s2c(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_group_avatar_info_change_s2c(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_info_change_s2c(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_32_avatar_info_change_s2c(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_64_avatar_info_change_s2c(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_avatar_info_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

decode_msg_avatar_head_change_c2s(Bin, TrUserData) -> dfp_read_field_def_avatar_head_change_c2s(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_avatar_head_change_c2s(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_avatar_head_change_c2s_head_id(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_avatar_head_change_c2s(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_avatar_head_change_c2s_head_border(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_avatar_head_change_c2s(<<>>, 0, 0, _, F@_1, F@_2, _) -> #avatar_head_change_c2s{head_id = F@_1, head_border = F@_2};
dfp_read_field_def_avatar_head_change_c2s(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_avatar_head_change_c2s(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_avatar_head_change_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_avatar_head_change_c2s(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_avatar_head_change_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_avatar_head_change_c2s_head_id(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
      16 -> d_field_avatar_head_change_c2s_head_border(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_head_change_c2s(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    1 -> skip_64_avatar_head_change_c2s(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    2 -> skip_length_delimited_avatar_head_change_c2s(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    3 -> skip_group_avatar_head_change_c2s(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    5 -> skip_32_avatar_head_change_c2s(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_avatar_head_change_c2s(<<>>, 0, 0, _, F@_1, F@_2, _) -> #avatar_head_change_c2s{head_id = F@_1, head_border = F@_2}.

d_field_avatar_head_change_c2s_head_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_avatar_head_change_c2s_head_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_avatar_head_change_c2s_head_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_head_change_c2s(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_avatar_head_change_c2s_head_border(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_avatar_head_change_c2s_head_border(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_avatar_head_change_c2s_head_border(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_head_change_c2s(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_avatar_head_change_c2s(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_avatar_head_change_c2s(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_avatar_head_change_c2s(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_avatar_head_change_c2s(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_avatar_head_change_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_avatar_head_change_c2s(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_avatar_head_change_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_head_change_c2s(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_avatar_head_change_c2s(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_head_change_c2s(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_avatar_head_change_c2s(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_avatar_head_change_c2s(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_avatar_head_change_c2s(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_avatar_head_change_c2s(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_avatar_head_change_s2c(Bin, TrUserData) -> dfp_read_field_def_avatar_head_change_s2c(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_avatar_head_change_s2c(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_avatar_head_change_s2c_result(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_avatar_head_change_s2c(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_avatar_head_change_s2c_head_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_avatar_head_change_s2c(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_avatar_head_change_s2c_head_border(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_avatar_head_change_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #avatar_head_change_s2c{result = F@_1, head_id = F@_2, head_border = F@_3};
dfp_read_field_def_avatar_head_change_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_avatar_head_change_s2c(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_avatar_head_change_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_avatar_head_change_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_avatar_head_change_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_avatar_head_change_s2c_result(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      16 -> d_field_avatar_head_change_s2c_head_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      24 -> d_field_avatar_head_change_s2c_head_border(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_head_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    1 -> skip_64_avatar_head_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    2 -> skip_length_delimited_avatar_head_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    3 -> skip_group_avatar_head_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    5 -> skip_32_avatar_head_change_s2c(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
	  end
    end;
dg_read_field_def_avatar_head_change_s2c(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #avatar_head_change_s2c{result = F@_1, head_id = F@_2, head_border = F@_3}.

d_field_avatar_head_change_s2c_result(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_avatar_head_change_s2c_result(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_avatar_head_change_s2c_result(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_head_change_s2c(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_avatar_head_change_s2c_head_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_avatar_head_change_s2c_head_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_avatar_head_change_s2c_head_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_head_change_s2c(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

d_field_avatar_head_change_s2c_head_border(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_avatar_head_change_s2c_head_border(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_avatar_head_change_s2c_head_border(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_head_change_s2c(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_avatar_head_change_s2c(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_avatar_head_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_avatar_head_change_s2c(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_avatar_head_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_avatar_head_change_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_avatar_head_change_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_avatar_head_change_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_head_change_s2c(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_avatar_head_change_s2c(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_head_change_s2c(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_avatar_head_change_s2c(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_avatar_head_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_avatar_head_change_s2c(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_avatar_head_change_s2c(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_avatar_heart_beat_c2s(Bin, TrUserData) -> dfp_read_field_def_avatar_heart_beat_c2s(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_avatar_heart_beat_c2s(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_avatar_heart_beat_c2s_svr_time(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_avatar_heart_beat_c2s(<<>>, 0, 0, _, F@_1, _) -> #avatar_heart_beat_c2s{svr_time = F@_1};
dfp_read_field_def_avatar_heart_beat_c2s(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_avatar_heart_beat_c2s(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_avatar_heart_beat_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_avatar_heart_beat_c2s(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_avatar_heart_beat_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_avatar_heart_beat_c2s_svr_time(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_heart_beat_c2s(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_avatar_heart_beat_c2s(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_avatar_heart_beat_c2s(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_avatar_heart_beat_c2s(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_avatar_heart_beat_c2s(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_avatar_heart_beat_c2s(<<>>, 0, 0, _, F@_1, _) -> #avatar_heart_beat_c2s{svr_time = F@_1}.

d_field_avatar_heart_beat_c2s_svr_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_avatar_heart_beat_c2s_svr_time(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_avatar_heart_beat_c2s_svr_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_heart_beat_c2s(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_avatar_heart_beat_c2s(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_avatar_heart_beat_c2s(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_avatar_heart_beat_c2s(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_c2s(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_avatar_heart_beat_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_avatar_heart_beat_c2s(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_avatar_heart_beat_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_heart_beat_c2s(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_avatar_heart_beat_c2s(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_heart_beat_c2s(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_avatar_heart_beat_c2s(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_c2s(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_avatar_heart_beat_c2s(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_c2s(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_avatar_heart_beat_s2c(Bin, TrUserData) -> dfp_read_field_def_avatar_heart_beat_s2c(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_avatar_heart_beat_s2c(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_avatar_heart_beat_s2c_svr_time(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_avatar_heart_beat_s2c(<<>>, 0, 0, _, F@_1, _) -> #avatar_heart_beat_s2c{svr_time = F@_1};
dfp_read_field_def_avatar_heart_beat_s2c(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_avatar_heart_beat_s2c(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_avatar_heart_beat_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_avatar_heart_beat_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_avatar_heart_beat_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_avatar_heart_beat_s2c_svr_time(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_avatar_heart_beat_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_avatar_heart_beat_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_avatar_heart_beat_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_avatar_heart_beat_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_avatar_heart_beat_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_avatar_heart_beat_s2c(<<>>, 0, 0, _, F@_1, _) -> #avatar_heart_beat_s2c{svr_time = F@_1}.

d_field_avatar_heart_beat_s2c_svr_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_avatar_heart_beat_s2c_svr_time(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_avatar_heart_beat_s2c_svr_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_avatar_heart_beat_s2c(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_avatar_heart_beat_s2c(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_avatar_heart_beat_s2c(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_avatar_heart_beat_s2c(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_avatar_heart_beat_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_avatar_heart_beat_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_avatar_heart_beat_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_avatar_heart_beat_s2c(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_avatar_heart_beat_s2c(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_avatar_heart_beat_s2c(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_avatar_heart_beat_s2c(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_avatar_heart_beat_s2c(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_avatar_heart_beat_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_svr_open_time_c2s(Bin, TrUserData) -> dfp_read_field_def_svr_open_time_c2s(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_svr_open_time_c2s(<<>>, 0, 0, _, _) -> #svr_open_time_c2s{};
dfp_read_field_def_svr_open_time_c2s(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_svr_open_time_c2s(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_svr_open_time_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_svr_open_time_c2s(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_svr_open_time_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_svr_open_time_c2s(Rest, 0, 0, Key bsr 3, TrUserData);
      1 -> skip_64_svr_open_time_c2s(Rest, 0, 0, Key bsr 3, TrUserData);
      2 -> skip_length_delimited_svr_open_time_c2s(Rest, 0, 0, Key bsr 3, TrUserData);
      3 -> skip_group_svr_open_time_c2s(Rest, 0, 0, Key bsr 3, TrUserData);
      5 -> skip_32_svr_open_time_c2s(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_svr_open_time_c2s(<<>>, 0, 0, _, _) -> #svr_open_time_c2s{}.

skip_varint_svr_open_time_c2s(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_svr_open_time_c2s(Rest, Z1, Z2, F, TrUserData);
skip_varint_svr_open_time_c2s(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_svr_open_time_c2s(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_svr_open_time_c2s(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_svr_open_time_c2s(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_svr_open_time_c2s(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_svr_open_time_c2s(Rest2, 0, 0, F, TrUserData).

skip_group_svr_open_time_c2s(Bin, _, Z2, FNum, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_svr_open_time_c2s(Rest, 0, Z2, FNum, TrUserData).

skip_32_svr_open_time_c2s(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_svr_open_time_c2s(Rest, Z1, Z2, F, TrUserData).

skip_64_svr_open_time_c2s(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_svr_open_time_c2s(Rest, Z1, Z2, F, TrUserData).

decode_msg_svr_open_time_s2c(Bin, TrUserData) -> dfp_read_field_def_svr_open_time_s2c(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_svr_open_time_s2c(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_svr_open_time_s2c_open_time(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_svr_open_time_s2c(<<>>, 0, 0, _, F@_1, _) -> #svr_open_time_s2c{open_time = F@_1};
dfp_read_field_def_svr_open_time_s2c(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_svr_open_time_s2c(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_svr_open_time_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_svr_open_time_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_svr_open_time_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_svr_open_time_s2c_open_time(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_svr_open_time_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_svr_open_time_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_svr_open_time_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_svr_open_time_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_svr_open_time_s2c(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_svr_open_time_s2c(<<>>, 0, 0, _, F@_1, _) -> #svr_open_time_s2c{open_time = F@_1}.

d_field_svr_open_time_s2c_open_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_svr_open_time_s2c_open_time(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_svr_open_time_s2c_open_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_svr_open_time_s2c(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_svr_open_time_s2c(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_svr_open_time_s2c(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_svr_open_time_s2c(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_svr_open_time_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_svr_open_time_s2c(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_svr_open_time_s2c(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_svr_open_time_s2c(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_svr_open_time_s2c(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_svr_open_time_s2c(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_svr_open_time_s2c(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_svr_open_time_s2c(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_svr_open_time_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_svr_open_time_s2c(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_svr_open_time_s2c(Rest, Z1, Z2, F, F@_1, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      avatar_info_s2c -> merge_msg_avatar_info_s2c(Prev, New, TrUserData);
      avatar_info_change_s2c -> merge_msg_avatar_info_change_s2c(Prev, New, TrUserData);
      avatar_head_change_c2s -> merge_msg_avatar_head_change_c2s(Prev, New, TrUserData);
      avatar_head_change_s2c -> merge_msg_avatar_head_change_s2c(Prev, New, TrUserData);
      avatar_heart_beat_c2s -> merge_msg_avatar_heart_beat_c2s(Prev, New, TrUserData);
      avatar_heart_beat_s2c -> merge_msg_avatar_heart_beat_s2c(Prev, New, TrUserData);
      svr_open_time_c2s -> merge_msg_svr_open_time_c2s(Prev, New, TrUserData);
      svr_open_time_s2c -> merge_msg_svr_open_time_s2c(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_avatar_info_s2c/3}).
merge_msg_avatar_info_s2c(#avatar_info_s2c{head = PFhead, head_border = PFhead_border, level = PFlevel, exp = PFexp, vip = PFvip},
			  #avatar_info_s2c{name = NFname, id = NFid, head = NFhead, head_border = NFhead_border, level = NFlevel, exp = NFexp, vip = NFvip}, _) ->
    #avatar_info_s2c{name = NFname, id = NFid,
		     head =
			 if NFhead =:= undefined -> PFhead;
			    true -> NFhead
			 end,
		     head_border =
			 if NFhead_border =:= undefined -> PFhead_border;
			    true -> NFhead_border
			 end,
		     level =
			 if NFlevel =:= undefined -> PFlevel;
			    true -> NFlevel
			 end,
		     exp =
			 if NFexp =:= undefined -> PFexp;
			    true -> NFexp
			 end,
		     vip =
			 if NFvip =:= undefined -> PFvip;
			    true -> NFvip
			 end}.

-compile({nowarn_unused_function,merge_msg_avatar_info_change_s2c/3}).
merge_msg_avatar_info_change_s2c(#avatar_info_change_s2c{head_id = PFhead_id, head_border = PFhead_border, level = PFlevel, exp = PFexp, vip = PFvip},
				 #avatar_info_change_s2c{name = NFname, id = NFid, head_id = NFhead_id, head_border = NFhead_border, level = NFlevel, exp = NFexp, vip = NFvip}, _) ->
    #avatar_info_change_s2c{name = NFname, id = NFid,
			    head_id =
				if NFhead_id =:= undefined -> PFhead_id;
				   true -> NFhead_id
				end,
			    head_border =
				if NFhead_border =:= undefined -> PFhead_border;
				   true -> NFhead_border
				end,
			    level =
				if NFlevel =:= undefined -> PFlevel;
				   true -> NFlevel
				end,
			    exp =
				if NFexp =:= undefined -> PFexp;
				   true -> NFexp
				end,
			    vip =
				if NFvip =:= undefined -> PFvip;
				   true -> NFvip
				end}.

-compile({nowarn_unused_function,merge_msg_avatar_head_change_c2s/3}).
merge_msg_avatar_head_change_c2s(#avatar_head_change_c2s{head_id = PFhead_id, head_border = PFhead_border}, #avatar_head_change_c2s{head_id = NFhead_id, head_border = NFhead_border}, _) ->
    #avatar_head_change_c2s{head_id =
				if NFhead_id =:= undefined -> PFhead_id;
				   true -> NFhead_id
				end,
			    head_border =
				if NFhead_border =:= undefined -> PFhead_border;
				   true -> NFhead_border
				end}.

-compile({nowarn_unused_function,merge_msg_avatar_head_change_s2c/3}).
merge_msg_avatar_head_change_s2c(#avatar_head_change_s2c{result = PFresult, head_id = PFhead_id, head_border = PFhead_border}, #avatar_head_change_s2c{result = NFresult, head_id = NFhead_id, head_border = NFhead_border}, _) ->
    #avatar_head_change_s2c{result =
				if NFresult =:= undefined -> PFresult;
				   true -> NFresult
				end,
			    head_id =
				if NFhead_id =:= undefined -> PFhead_id;
				   true -> NFhead_id
				end,
			    head_border =
				if NFhead_border =:= undefined -> PFhead_border;
				   true -> NFhead_border
				end}.

-compile({nowarn_unused_function,merge_msg_avatar_heart_beat_c2s/3}).
merge_msg_avatar_heart_beat_c2s(#avatar_heart_beat_c2s{}, #avatar_heart_beat_c2s{svr_time = NFsvr_time}, _) -> #avatar_heart_beat_c2s{svr_time = NFsvr_time}.

-compile({nowarn_unused_function,merge_msg_avatar_heart_beat_s2c/3}).
merge_msg_avatar_heart_beat_s2c(#avatar_heart_beat_s2c{}, #avatar_heart_beat_s2c{svr_time = NFsvr_time}, _) -> #avatar_heart_beat_s2c{svr_time = NFsvr_time}.

-compile({nowarn_unused_function,merge_msg_svr_open_time_c2s/3}).
merge_msg_svr_open_time_c2s(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_svr_open_time_s2c/3}).
merge_msg_svr_open_time_s2c(#svr_open_time_s2c{}, #svr_open_time_s2c{open_time = NFopen_time}, _) -> #svr_open_time_s2c{open_time = NFopen_time}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      avatar_info_s2c -> v_msg_avatar_info_s2c(Msg, [MsgName], TrUserData);
      avatar_info_change_s2c -> v_msg_avatar_info_change_s2c(Msg, [MsgName], TrUserData);
      avatar_head_change_c2s -> v_msg_avatar_head_change_c2s(Msg, [MsgName], TrUserData);
      avatar_head_change_s2c -> v_msg_avatar_head_change_s2c(Msg, [MsgName], TrUserData);
      avatar_heart_beat_c2s -> v_msg_avatar_heart_beat_c2s(Msg, [MsgName], TrUserData);
      avatar_heart_beat_s2c -> v_msg_avatar_heart_beat_s2c(Msg, [MsgName], TrUserData);
      svr_open_time_c2s -> v_msg_svr_open_time_c2s(Msg, [MsgName], TrUserData);
      svr_open_time_s2c -> v_msg_svr_open_time_s2c(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_avatar_info_s2c/3}).
-dialyzer({nowarn_function,v_msg_avatar_info_s2c/3}).
v_msg_avatar_info_s2c(#avatar_info_s2c{name = F1, id = F2, head = F3, head_border = F4, level = F5, exp = F6, vip = F7}, Path, TrUserData) ->
    v_type_string(F1, [name | Path], TrUserData),
    v_type_int64(F2, [id | Path], TrUserData),
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [head | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_int32(F4, [head_border | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_int32(F5, [level | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_int32(F6, [exp | Path], TrUserData)
    end,
    if F7 == undefined -> ok;
       true -> v_type_int32(F7, [vip | Path], TrUserData)
    end,
    ok;
v_msg_avatar_info_s2c(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_info_s2c}, X, Path).

-compile({nowarn_unused_function,v_msg_avatar_info_change_s2c/3}).
-dialyzer({nowarn_function,v_msg_avatar_info_change_s2c/3}).
v_msg_avatar_info_change_s2c(#avatar_info_change_s2c{name = F1, id = F2, head_id = F3, head_border = F4, level = F5, exp = F6, vip = F7}, Path, TrUserData) ->
    v_type_string(F1, [name | Path], TrUserData),
    v_type_int64(F2, [id | Path], TrUserData),
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [head_id | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_int32(F4, [head_border | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_int32(F5, [level | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_int32(F6, [exp | Path], TrUserData)
    end,
    if F7 == undefined -> ok;
       true -> v_type_int32(F7, [vip | Path], TrUserData)
    end,
    ok;
v_msg_avatar_info_change_s2c(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_info_change_s2c}, X, Path).

-compile({nowarn_unused_function,v_msg_avatar_head_change_c2s/3}).
-dialyzer({nowarn_function,v_msg_avatar_head_change_c2s/3}).
v_msg_avatar_head_change_c2s(#avatar_head_change_c2s{head_id = F1, head_border = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [head_id | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_int32(F2, [head_border | Path], TrUserData)
    end,
    ok;
v_msg_avatar_head_change_c2s(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_head_change_c2s}, X, Path).

-compile({nowarn_unused_function,v_msg_avatar_head_change_s2c/3}).
-dialyzer({nowarn_function,v_msg_avatar_head_change_s2c/3}).
v_msg_avatar_head_change_s2c(#avatar_head_change_s2c{result = F1, head_id = F2, head_border = F3}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [result | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_int32(F2, [head_id | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [head_border | Path], TrUserData)
    end,
    ok;
v_msg_avatar_head_change_s2c(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_head_change_s2c}, X, Path).

-compile({nowarn_unused_function,v_msg_avatar_heart_beat_c2s/3}).
-dialyzer({nowarn_function,v_msg_avatar_heart_beat_c2s/3}).
v_msg_avatar_heart_beat_c2s(#avatar_heart_beat_c2s{svr_time = F1}, Path, TrUserData) -> v_type_int32(F1, [svr_time | Path], TrUserData), ok;
v_msg_avatar_heart_beat_c2s(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_heart_beat_c2s}, X, Path).

-compile({nowarn_unused_function,v_msg_avatar_heart_beat_s2c/3}).
-dialyzer({nowarn_function,v_msg_avatar_heart_beat_s2c/3}).
v_msg_avatar_heart_beat_s2c(#avatar_heart_beat_s2c{svr_time = F1}, Path, TrUserData) -> v_type_int32(F1, [svr_time | Path], TrUserData), ok;
v_msg_avatar_heart_beat_s2c(X, Path, _TrUserData) -> mk_type_error({expected_msg, avatar_heart_beat_s2c}, X, Path).

-compile({nowarn_unused_function,v_msg_svr_open_time_c2s/3}).
-dialyzer({nowarn_function,v_msg_svr_open_time_c2s/3}).
v_msg_svr_open_time_c2s(#svr_open_time_c2s{}, _Path, _) -> ok;
v_msg_svr_open_time_c2s(X, Path, _TrUserData) -> mk_type_error({expected_msg, svr_open_time_c2s}, X, Path).

-compile({nowarn_unused_function,v_msg_svr_open_time_s2c/3}).
-dialyzer({nowarn_function,v_msg_svr_open_time_s2c/3}).
v_msg_svr_open_time_s2c(#svr_open_time_s2c{open_time = F1}, Path, TrUserData) -> v_type_int32(F1, [open_time | Path], TrUserData), ok;
v_msg_svr_open_time_s2c(X, Path, _TrUserData) -> mk_type_error({expected_msg, svr_open_time_s2c}, X, Path).

-compile({nowarn_unused_function,v_type_int32/3}).
-dialyzer({nowarn_function,v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData) when -2147483648 =< N, N =< 2147483647 -> ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int32, signed, 32}, N, Path);
v_type_int32(X, Path, _TrUserData) -> mk_type_error({bad_integer, int32, signed, 32}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) -> Path2 = prettify_path(Path), erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, avatar_info_s2c},
      [#field{name = name, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = id, fnum = 2, rnum = 3, type = int64, occurrence = required, opts = []},
       #field{name = head, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []},
       #field{name = level, fnum = 5, rnum = 6, type = int32, occurrence = optional, opts = []}, #field{name = exp, fnum = 6, rnum = 7, type = int32, occurrence = optional, opts = []},
       #field{name = vip, fnum = 7, rnum = 8, type = int32, occurrence = optional, opts = []}]},
     {{msg, avatar_info_change_s2c},
      [#field{name = name, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = id, fnum = 2, rnum = 3, type = int64, occurrence = required, opts = []},
       #field{name = head_id, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []},
       #field{name = level, fnum = 5, rnum = 6, type = int32, occurrence = optional, opts = []}, #field{name = exp, fnum = 6, rnum = 7, type = int32, occurrence = optional, opts = []},
       #field{name = vip, fnum = 7, rnum = 8, type = int32, occurrence = optional, opts = []}]},
     {{msg, avatar_head_change_c2s}, [#field{name = head_id, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []}]},
     {{msg, avatar_head_change_s2c},
      [#field{name = result, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = head_id, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
       #field{name = head_border, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}]},
     {{msg, avatar_heart_beat_c2s}, [#field{name = svr_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}]},
     {{msg, avatar_heart_beat_s2c}, [#field{name = svr_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}]}, {{msg, svr_open_time_c2s}, []},
     {{msg, svr_open_time_s2c}, [#field{name = open_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}]}].


get_msg_names() -> [avatar_info_s2c, avatar_info_change_s2c, avatar_head_change_c2s, avatar_head_change_s2c, avatar_heart_beat_c2s, avatar_heart_beat_s2c, svr_open_time_c2s, svr_open_time_s2c].


get_group_names() -> [].


get_msg_or_group_names() -> [avatar_info_s2c, avatar_info_change_s2c, avatar_head_change_c2s, avatar_head_change_s2c, avatar_heart_beat_c2s, avatar_heart_beat_s2c, svr_open_time_c2s, svr_open_time_s2c].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def(avatar_info_s2c) ->
    [#field{name = name, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = id, fnum = 2, rnum = 3, type = int64, occurrence = required, opts = []},
     #field{name = head, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []},
     #field{name = level, fnum = 5, rnum = 6, type = int32, occurrence = optional, opts = []}, #field{name = exp, fnum = 6, rnum = 7, type = int32, occurrence = optional, opts = []},
     #field{name = vip, fnum = 7, rnum = 8, type = int32, occurrence = optional, opts = []}];
find_msg_def(avatar_info_change_s2c) ->
    [#field{name = name, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = id, fnum = 2, rnum = 3, type = int64, occurrence = required, opts = []},
     #field{name = head_id, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []},
     #field{name = level, fnum = 5, rnum = 6, type = int32, occurrence = optional, opts = []}, #field{name = exp, fnum = 6, rnum = 7, type = int32, occurrence = optional, opts = []},
     #field{name = vip, fnum = 7, rnum = 8, type = int32, occurrence = optional, opts = []}];
find_msg_def(avatar_head_change_c2s) -> [#field{name = head_id, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = head_border, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []}];
find_msg_def(avatar_head_change_s2c) ->
    [#field{name = result, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = head_id, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
     #field{name = head_border, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []}];
find_msg_def(avatar_heart_beat_c2s) -> [#field{name = svr_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}];
find_msg_def(avatar_heart_beat_s2c) -> [#field{name = svr_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}];
find_msg_def(svr_open_time_c2s) -> [];
find_msg_def(svr_open_time_s2c) -> [#field{name = open_time, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"yy.proto.avatar_info_s2c">>) -> avatar_info_s2c;
fqbin_to_msg_name(<<"yy.proto.avatar_info_change_s2c">>) -> avatar_info_change_s2c;
fqbin_to_msg_name(<<"yy.proto.avatar_head_change_c2s">>) -> avatar_head_change_c2s;
fqbin_to_msg_name(<<"yy.proto.avatar_head_change_s2c">>) -> avatar_head_change_s2c;
fqbin_to_msg_name(<<"yy.proto.avatar_heart_beat_c2s">>) -> avatar_heart_beat_c2s;
fqbin_to_msg_name(<<"yy.proto.avatar_heart_beat_s2c">>) -> avatar_heart_beat_s2c;
fqbin_to_msg_name(<<"yy.proto.svr_open_time_c2s">>) -> svr_open_time_c2s;
fqbin_to_msg_name(<<"yy.proto.svr_open_time_s2c">>) -> svr_open_time_s2c;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(avatar_info_s2c) -> <<"yy.proto.avatar_info_s2c">>;
msg_name_to_fqbin(avatar_info_change_s2c) -> <<"yy.proto.avatar_info_change_s2c">>;
msg_name_to_fqbin(avatar_head_change_c2s) -> <<"yy.proto.avatar_head_change_c2s">>;
msg_name_to_fqbin(avatar_head_change_s2c) -> <<"yy.proto.avatar_head_change_s2c">>;
msg_name_to_fqbin(avatar_heart_beat_c2s) -> <<"yy.proto.avatar_heart_beat_c2s">>;
msg_name_to_fqbin(avatar_heart_beat_s2c) -> <<"yy.proto.avatar_heart_beat_s2c">>;
msg_name_to_fqbin(svr_open_time_c2s) -> <<"yy.proto.svr_open_time_c2s">>;
msg_name_to_fqbin(svr_open_time_s2c) -> <<"yy.proto.svr_open_time_s2c">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'yy.proto'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "avatar.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["avatar.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["avatar"].


get_msg_containment("avatar") -> [avatar_head_change_c2s, avatar_head_change_s2c, avatar_heart_beat_c2s, avatar_heart_beat_s2c, avatar_info_change_s2c, avatar_info_s2c, svr_open_time_c2s, svr_open_time_s2c];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("avatar") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("avatar") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("avatar") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("avatar") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"yy.proto.svr_open_time_s2c">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.svr_open_time_c2s">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_info_s2c">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_info_change_s2c">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_heart_beat_s2c">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_heart_beat_c2s">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_head_change_s2c">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(<<"yy.proto.avatar_head_change_c2s">>) -> "avatar";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.19.6".

gpb_version_as_list() ->
    [4,19,6].

gpb_version_source() ->
    "file".
