%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(friend_pb).
-define(friend_pb, true).

-define(friend_pb_gpb_version, "4.19.6").

-ifndef('FRIEND_APPLY_LIST_C2S_PB_H').
-define('FRIEND_APPLY_LIST_C2S_PB_H', true).
-record(friend_apply_list_c2s,
        {
        }).
-endif.

-ifndef('FRIEND_APPLY_LIST_S2C_PB_H').
-define('FRIEND_APPLY_LIST_S2C_PB_H', true).
-record(friend_apply_list_s2c,
        {apply_list = []        :: [friend_pb:p_applyInfo()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_APPLYINFO_PB_H').
-define('P_APPLYINFO_PB_H', true).
-record(p_applyInfo,
        {id                     :: integer() | undefined, % = 1, required, 64 bits
         role_id                :: integer() | undefined, % = 2, required, 64 bits
         name                   :: unicode:chardata() | undefined, % = 3, optional
         gender                 :: integer() | undefined % = 4, optional, 32 bits
        }).
-endif.

-ifndef('FRIEND_NEW_APPLY_C2S_PB_H').
-define('FRIEND_NEW_APPLY_C2S_PB_H', true).
-record(friend_new_apply_c2s,
        {friend_uid             :: integer() | undefined % = 1, required, 64 bits
        }).
-endif.

-ifndef('FRIEND_NEW_APPLY_S2C_PB_H').
-define('FRIEND_NEW_APPLY_S2C_PB_H', true).
-record(friend_new_apply_s2c,
        {success                :: boolean() | 0 | 1 | undefined % = 1, required
        }).
-endif.

-ifndef('FRIEND_HANDLE_APPLY_C2S_PB_H').
-define('FRIEND_HANDLE_APPLY_C2S_PB_H', true).
-record(friend_handle_apply_c2s,
        {apply_id               :: integer() | undefined, % = 1, required, 64 bits
         is_accept              :: boolean() | 0 | 1 | undefined % = 2, required
        }).
-endif.

-ifndef('FRIEND_HANDLE_APPLY_S2C_PB_H').
-define('FRIEND_HANDLE_APPLY_S2C_PB_H', true).
-record(friend_handle_apply_s2c,
        {success                :: boolean() | 0 | 1 | undefined % = 1, required
        }).
-endif.

-ifndef('FRIEND_LIST_C2S_PB_H').
-define('FRIEND_LIST_C2S_PB_H', true).
-record(friend_list_c2s,
        {
        }).
-endif.

-ifndef('FRIEND_LIST_S2C_PB_H').
-define('FRIEND_LIST_S2C_PB_H', true).
-record(friend_list_s2c,
        {friend_list = []       :: [friend_pb:p_friendInfo()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_FRIENDINFO_PB_H').
-define('P_FRIENDINFO_PB_H', true).
-record(p_friendInfo,
        {role_id                :: integer() | undefined, % = 1, required, 64 bits
         name                   :: unicode:chardata() | undefined, % = 2, optional
         gender                 :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-endif.
