%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(gm_pb).
-define(gm_pb, true).

-define(gm_pb_gpb_version, "4.19.6").

-ifndef('GM_CMD_C2S_PB_H').
-define('GM_CMD_C2S_PB_H', true).
-record(gm_cmd_c2s,
        {cmd                    :: unicode:chardata() | undefined % = 1, required
        }).
-endif.

-endif.
