%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.19.6").

-ifndef('CONNECT_ACTIVE_S2C_PB_H').
-define('CONNECT_ACTIVE_S2C_PB_H', true).
-record(connect_active_s2c,
        {result_code            :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('ROLE_LOGIN_C2S_PB_H').
-define('ROLE_LOGIN_C2S_PB_H', true).
-record(role_login_c2s,
        {uid                    :: integer() | undefined, % = 1, required, 32 bits
         uname                  :: unicode:chardata() | undefined, % = 2, required
         plat                   :: unicode:chardata() | undefined, % = 3, required
         game_id                :: unicode:chardata() | undefined, % = 4, required
         svrId                  :: integer() | undefined, % = 6, required, 32 bits
         machine_info           :: login_pb:p_machineInfo() | undefined % = 7, optional
        }).
-endif.

-ifndef('P_MACHINEINFO_PB_H').
-define('P_MACHINEINFO_PB_H', true).
-record(p_machineInfo,
        {device                 :: unicode:chardata() | undefined, % = 1, optional
         device_id              :: unicode:chardata() | undefined, % = 2, optional
         device_name            :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('ROLE_RECONNECT_C2S_PB_H').
-define('ROLE_RECONNECT_C2S_PB_H', true).
-record(role_reconnect_c2s,
        {uid                    :: integer() | undefined, % = 1, required, 32 bits
         svr_id                 :: integer() | undefined, % = 2, required, 32 bits
         client_mid             :: integer() | undefined, % = 3, required, 32 bits
         svr_mid                :: integer() | undefined % = 4, required, 32 bits
        }).
-endif.

-ifndef('ROLE_RECONNECT_S2C_PB_H').
-define('ROLE_RECONNECT_S2C_PB_H', true).
-record(role_reconnect_s2c,
        {need_login             :: boolean() | 0 | 1 | undefined, % = 1, required
         has_pack               :: boolean() | 0 | 1 | undefined, % = 2, required
         last_client_mid        :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-ifndef('RESET_GW_MID_C2S_PB_H').
-define('RESET_GW_MID_C2S_PB_H', true).
-record(reset_gw_mid_c2s,
        {mid                    :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('CREATE_ROLE_C2S_PB_H').
-define('CREATE_ROLE_C2S_PB_H', true).
-record(create_role_c2s,
        {name                   :: unicode:chardata() | undefined, % = 1, required
         gender                 :: integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-ifndef('CREATE_ROLE_S2C_PB_H').
-define('CREATE_ROLE_S2C_PB_H', true).
-record(create_role_s2c,
        {result_code            :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('ROLE_LOGIN_S2C_PB_H').
-define('ROLE_LOGIN_S2C_PB_H', true).
-record(role_login_s2c,
        {result_code            :: integer() | undefined, % = 1, required, 32 bits
         main_svr_id            :: integer() | undefined, % = 2, optional, 32 bits
         exist_role             :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('ROLE_INFO_S2C_PB_H').
-define('ROLE_INFO_S2C_PB_H', true).
-record(role_info_s2c,
        {role_info              :: login_pb:p_roleInfo() | undefined % = 1, optional
        }).
-endif.

-ifndef('P_ROLEINFO_PB_H').
-define('P_ROLEINFO_PB_H', true).
-record(p_roleInfo,
        {role_id                :: integer() | undefined, % = 1, required, 64 bits
         name                   :: unicode:chardata() | undefined, % = 2, optional
         gender                 :: integer() | undefined, % = 3, optional, 32 bits
         exp                    :: integer() | undefined, % = 4, optional, 32 bits
         level                  :: integer() | undefined, % = 5, optional, 32 bits
         vip                    :: integer() | undefined % = 6, optional, 32 bits
        }).
-endif.

-ifndef('ROLE_LOGOUT_C2S_PB_H').
-define('ROLE_LOGOUT_C2S_PB_H', true).
-record(role_logout_c2s,
        {
        }).
-endif.

-ifndef('ROLE_LOGOUT_S2C_PB_H').
-define('ROLE_LOGOUT_S2C_PB_H', true).
-record(role_logout_s2c,
        {code                   :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-endif.
