%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(mail_pb).
-define(mail_pb, true).

-define(mail_pb_gpb_version, "4.19.6").

-ifndef('MAIL_LIST_C2S_PB_H').
-define('MAIL_LIST_C2S_PB_H', true).
-record(mail_list_c2s,
        {
        }).
-endif.

-ifndef('MAIL_LIST_S2C_PB_H').
-define('MAIL_LIST_S2C_PB_H', true).
-record(mail_list_s2c,
        {mail_list = []         :: [mail_pb:p_mailInfo()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_MAILINFO_PB_H').
-define('P_MAILINFO_PB_H', true).
-record(p_mailInfo,
        {id                     :: integer() | undefined, % = 1, required, 64 bits
         type                   :: integer() | undefined, % = 2, required, 32 bits
         from_id                :: integer() | undefined, % = 3, optional, 64 bits
         send_time              :: integer() | undefined, % = 4, optional, 64 bits
         title                  :: unicode:chardata() | undefined, % = 5, optional
         content                :: unicode:chardata() | undefined, % = 6, optional
         is_read                :: boolean() | 0 | 1 | undefined, % = 7, optional
         is_extract             :: boolean() | 0 | 1 | undefined % = 8, optional
        }).
-endif.

-ifndef('MAIL_OPEN_C2S_PB_H').
-define('MAIL_OPEN_C2S_PB_H', true).
-record(mail_open_c2s,
        {mail_id                :: integer() | undefined % = 1, required, 64 bits
        }).
-endif.

-ifndef('MAIL_OPEN_S2C_PB_H').
-define('MAIL_OPEN_S2C_PB_H', true).
-record(mail_open_s2c,
        {success                :: boolean() | 0 | 1 | undefined % = 1, required
        }).
-endif.

-ifndef('CLEAN_MAILS_C2S_PB_H').
-define('CLEAN_MAILS_C2S_PB_H', true).
-record(clean_mails_c2s,
        {
        }).
-endif.

-endif.
