%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(misc_pb).
-define(misc_pb, true).

-define(misc_pb_gpb_version, "4.19.6").

-ifndef('SVR_ERROR_S2C_PB_H').
-define('SVR_ERROR_S2C_PB_H', true).
-record(svr_error_s2c,
        {msg                    :: unicode:chardata() | undefined % = 1, required
        }).
-endif.

-ifndef('TIPS_S2C_PB_H').
-define('TIPS_S2C_PB_H', true).
-record(tips_s2c,
        {msg                    :: misc_pb:p_msg() | undefined % = 1, required
        }).
-endif.

-ifndef('P_MSG_PB_H').
-define('P_MSG_PB_H', true).
-record(p_msg,
        {type                   :: non_neg_integer() | undefined, % = 1, required, 32 bits
         id                     :: non_neg_integer() | undefined, % = 2, required, 32 bits
         param                  :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-endif.
