%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(avatar_pb).
-define(avatar_pb, true).

-define(avatar_pb_gpb_version, "4.19.6").

-ifndef('AVATAR_INFO_S2C_PB_H').
-define('AVATAR_INFO_S2C_PB_H', true).
-record(avatar_info_s2c,
        {name                   :: unicode:chardata() | undefined, % = 1, required
         id                     :: integer() | undefined, % = 2, required, 64 bits
         head                   :: integer() | undefined, % = 3, optional, 32 bits
         head_border            :: integer() | undefined, % = 4, optional, 32 bits
         level                  :: integer() | undefined, % = 5, optional, 32 bits
         exp                    :: integer() | undefined, % = 6, optional, 32 bits
         vip                    :: integer() | undefined % = 7, optional, 32 bits
        }).
-endif.

-ifndef('AVATAR_INFO_CHANGE_S2C_PB_H').
-define('AVATAR_INFO_CHANGE_S2C_PB_H', true).
-record(avatar_info_change_s2c,
        {name                   :: unicode:chardata() | undefined, % = 1, required
         id                     :: integer() | undefined, % = 2, required, 64 bits
         head_id                :: integer() | undefined, % = 3, optional, 32 bits
         head_border            :: integer() | undefined, % = 4, optional, 32 bits
         level                  :: integer() | undefined, % = 5, optional, 32 bits
         exp                    :: integer() | undefined, % = 6, optional, 32 bits
         vip                    :: integer() | undefined % = 7, optional, 32 bits
        }).
-endif.

-ifndef('AVATAR_HEAD_CHANGE_C2S_PB_H').
-define('AVATAR_HEAD_CHANGE_C2S_PB_H', true).
-record(avatar_head_change_c2s,
        {head_id                :: integer() | undefined, % = 1, optional, 32 bits
         head_border            :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-ifndef('AVATAR_HEAD_CHANGE_S2C_PB_H').
-define('AVATAR_HEAD_CHANGE_S2C_PB_H', true).
-record(avatar_head_change_s2c,
        {result                 :: integer() | undefined, % = 1, optional, 32 bits
         head_id                :: integer() | undefined, % = 2, optional, 32 bits
         head_border            :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-ifndef('AVATAR_HEART_BEAT_C2S_PB_H').
-define('AVATAR_HEART_BEAT_C2S_PB_H', true).
-record(avatar_heart_beat_c2s,
        {svr_time               :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('AVATAR_HEART_BEAT_S2C_PB_H').
-define('AVATAR_HEART_BEAT_S2C_PB_H', true).
-record(avatar_heart_beat_s2c,
        {svr_time               :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('SVR_OPEN_TIME_C2S_PB_H').
-define('SVR_OPEN_TIME_C2S_PB_H', true).
-record(svr_open_time_c2s,
        {
        }).
-endif.

-ifndef('SVR_OPEN_TIME_S2C_PB_H').
-define('SVR_OPEN_TIME_S2C_PB_H', true).
-record(svr_open_time_s2c,
        {open_time              :: integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-endif.
