%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(comm_pb).
-define(comm_pb, true).

-define(comm_pb_gpb_version, "4.19.6").

-ifndef('P_KV_INT_PB_H').
-define('P_KV_INT_PB_H', true).
-record(p_kv_int,
        {key                    :: integer() | undefined, % = 1, optional, 32 bits
         value                  :: integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-endif.
