%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(prop_pb).
-define(prop_pb, true).

-define(prop_pb_gpb_version, "4.19.6").

-ifndef('ROLE_PROP_PLAYER_C2S_PB_H').
-define('ROLE_PROP_PLAYER_C2S_PB_H', true).
-record(role_prop_player_c2s,
        {
        }).
-endif.

-ifndef('ROLE_PROP_PLAYER_S2C_PB_H').
-define('ROLE_PROP_PLAYER_S2C_PB_H', true).
-record(role_prop_player_s2c,
        {kv_list = []           :: [prop_pb:p_kv_int()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('ROLE_PROP_PLAYER_CHANGED_S2C_PB_H').
-define('ROLE_PROP_PLAYER_CHANGED_S2C_PB_H', true).
-record(role_prop_player_changed_s2c,
        {kv_list = []           :: [prop_pb:p_kv_int()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_KV_INT_PB_H').
-define('P_KV_INT_PB_H', true).
-record(p_kv_int,
        {key                    :: integer() | undefined, % = 1, optional, 32 bits
         value                  :: integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-endif.
