%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(res_pb).
-define(res_pb, true).

-define(res_pb_gpb_version, "4.19.6").

-ifndef('RES_LIST_BAG_C2S_PB_H').
-define('RES_LIST_BAG_C2S_PB_H', true).
-record(res_list_bag_c2s,
        {
        }).
-endif.

-ifndef('RES_LIST_BAG_S2C_PB_H').
-define('RES_LIST_BAG_S2C_PB_H', true).
-record(res_list_bag_s2c,
        {bagItem_list = []      :: [res_pb:p_bag_item()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_BAG_ITEM_PB_H').
-define('P_BAG_ITEM_PB_H', true).
-record(p_bag_item,
        {id                     :: integer() | undefined, % = 1, required, 64 bits
         cfgId                  :: integer() | undefined, % = 2, optional, 32 bits
         count                  :: integer() | undefined, % = 3, optional, 64 bits
         max_count              :: integer() | undefined, % = 4, optional, 64 bits
         expired_time           :: integer() | undefined, % = 5, optional, 64 bits
         is_bind                :: boolean() | 0 | 1 | undefined % = 6, optional
        }).
-endif.

-ifndef('RES_LIST_WALLET_C2S_PB_H').
-define('RES_LIST_WALLET_C2S_PB_H', true).
-record(res_list_wallet_c2s,
        {
        }).
-endif.

-ifndef('RES_LIST_WALLET_S2C_PB_H').
-define('RES_LIST_WALLET_S2C_PB_H', true).
-record(res_list_wallet_s2c,
        {walletItem_list = []   :: [res_pb:p_wallet_item()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('P_WALLET_ITEM_PB_H').
-define('P_WALLET_ITEM_PB_H', true).
-record(p_wallet_item,
        {id                     :: integer() | undefined, % = 1, required, 64 bits
         bind_count             :: integer() | undefined, % = 2, required, 64 bits
         unbind_count           :: integer() | undefined % = 3, required, 64 bits
        }).
-endif.

-ifndef('RES_USE_BAG_ITEM_C2S_PB_H').
-define('RES_USE_BAG_ITEM_C2S_PB_H', true).
-record(res_use_bag_item_c2s,
        {cfg_id                 :: integer() | undefined, % = 1, required, 32 bits
         count                  :: integer() | undefined % = 2, required, 64 bits
        }).
-endif.

-ifndef('RES_USE_BAG_ITEM_S2C_PB_H').
-define('RES_USE_BAG_ITEM_S2C_PB_H', true).
-record(res_use_bag_item_s2c,
        {success                :: boolean() | 0 | 1 | undefined % = 1, required
        }).
-endif.

-ifndef('RES_USE_WALLET_ITEM_C2S_PB_H').
-define('RES_USE_WALLET_ITEM_C2S_PB_H', true).
-record(res_use_wallet_item_c2s,
        {cfg_id                 :: integer() | undefined, % = 1, required, 32 bits
         count                  :: integer() | undefined % = 2, required, 64 bits
        }).
-endif.

-ifndef('RES_USE_WALLET_ITEM_S2C_PB_H').
-define('RES_USE_WALLET_ITEM_S2C_PB_H', true).
-record(res_use_wallet_item_s2c,
        {success                :: boolean() | 0 | 1 | undefined % = 1, required
        }).
-endif.

-endif.
